version: "3"

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand('ping').ok" ]
      interval: 30s
      timeout: 10s
      retries: 5